-- ============================================================================
-- Parametri del server PostgreSQL di produzione — dichiarati qui, non solo
-- sulla macchina.
--
-- #220 W1.3 (rilievo F5-03) · W1.6 (rilievi F8-10, F4-04)
--
-- PERCHE' QUESTO FILE ESISTE. Misurato il 2026-08-20: `postgresql.auto.conf`
-- sulla VM era **vuoto** e nel repo non c'era alcuna configurazione di server.
-- Ogni parametro non-default viveva quindi in un solo posto — la macchina — e
-- nessuno poteva dire, leggendo il repo, come fosse configurata la produzione.
-- Un `ALTER SYSTEM` battuto a mano una sera non lascia traccia da nessun'altra
-- parte: e' lo stesso difetto che W1.7 corregge per le unit systemd.
--
-- COME SI APPLICA (serve superuser: l'utente applicativo `heuresys` non lo e')
--     ssh oracle-vm-default 'sudo -u postgres psql -f -' < deploy/postgres/parametri-server.sql
--     ssh oracle-vm-default 'sudo -u postgres psql -tAc "SELECT pg_reload_conf()"'
--
-- ⚠ `ALTER SYSTEM` NON GIRA DENTRO UNA TRANSAZIONE: un `psql -c` che ne
-- concatena piu' d'uno con il punto e virgola fallisce in blocco. Uno per
-- comando, oppure — come qui — un file, dove psql li esegue separatamente.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Tracciare chi si connette (F5-03)
--
-- Misurato prima: log_connections=off, log_disconnections=off. Il database non
-- conservava alcuna traccia di chi apriva una sessione. Non era un guasto —
-- era un'assenza, ed e' la ragione per cui nessuno se n'era accorto.
-- ---------------------------------------------------------------------------
ALTER SYSTEM SET log_connections = 'on';
ALTER SYSTEM SET log_disconnections = 'on';

-- Il prefisso di riga decide se un log e' leggibile o solo voluminoso. Al
-- default (`%m [%p] %q%u@%d`) mancano l'host di provenienza e il nome
-- dell'applicazione: senza, «chi si e' connesso» resta senza risposta proprio
-- quando serve. `%h` e `%a` la danno — verificato nel log reale, dove ora si
-- legge `... 127.0.0.1 psql LOG: connection authorized ...`.
ALTER SYSTEM SET log_line_prefix = '%m [%p] %q%u@%d %h %a ';

-- ---------------------------------------------------------------------------
-- 2. Le query lente (F5-03)
--
-- Misurato prima: -1, cioe' spento. La soglia e' 1 secondo, non 0: registrare
-- OGNI istruzione su un database di produzione produce un volume che nessuno
-- legge e che consuma il disco — e un log che nessuno legge non e' un presidio,
-- e' un costo. Il disco misurato lo stesso giorno era al 77% (23G liberi su
-- 96G): ampio, ma non tale da giustificare la registrazione integrale.
-- ---------------------------------------------------------------------------
ALTER SYSTEM SET log_min_duration_statement = '1000ms';

-- ---------------------------------------------------------------------------
-- 3. Il tempo dentro le funzioni PL (F8-10)
--
-- Context `superuser`, NON `postmaster`: entra in vigore con il solo reload.
-- La prima stesura di questo file lo aveva messo fra i parametri che pretendono
-- un riavvio — sbagliato, e scoperto solo perche' dopo il reload
-- `pending_restart` risultava gia' `false`. Il context non si ricorda a
-- memoria, si chiede:
--     SELECT name, context FROM pg_settings WHERE name = '<nome>';
-- ---------------------------------------------------------------------------
ALTER SYSTEM SET track_functions = 'pl';

-- ===========================================================================
-- 4. IL PRIMO DEI PARAMETRI CHE PRETENDONO UN RESTART (context = postmaster)
--
-- ⚠ Questa intestazione diceva «L'UNICO» fino a S1077, quando il blocco 5 ne ha
-- aggiunto un secondo. Un file che dichiara «uno solo» e ne contiene due mente al
-- prossimo che lo legge — percio' si emenda la frase, non si aggiunge in fondo
-- sperando che se ne accorga.
--
-- Scritto, ma NON attivo finche' PostgreSQL non viene riavviato. Il riavvio e'
-- F4 di #220: pianificato e annunciato, mai di passaggio — e' la produzione, e
-- ogni connessione aperta cade.
--
--     SELECT name, setting, pending_restart FROM pg_settings
--      WHERE name = 'pg_stat_statements.max';
-- `pending_restart = true` significa: scritto, non ancora in vigore.
--
-- F4-04 — il numero di istruzioni distinte che `pg_stat_statements` conserva.
-- Al default (5.000) le istruzioni meno frequenti vengono sfrattate, e sono
-- proprio quelle che si vorrebbe vedere quando si cerca una lentezza rara.
-- ===========================================================================
ALTER SYSTEM SET pg_stat_statements.max = '10000';

-- ===========================================================================
-- 5. LA MEMORIA DEL MOTORE, SU UNA MACCHINA CHE NON E' SOLO SUA
--    #223 F4 · rilievi F8-06 e F8-14 · S1077, 2026-08-21
--
-- MISURATO PRIMA, sulla macchina viva, non dedotto dal dossier:
--   · RAM 11.927 MB · available 9.631 MB · used 2.296 · buff/cache 8.242
--   · swap in uso 1.461 MB su 8.192 — c'e' stata pressione in passato
--   · 2 processori · load average 0.08 · 8 giorni di uptime
--   · database: heuresys_platform 1.113 MB + heuresys_advanced 1.040 MB
--     + heuresys_ci 1.025 MB = ~3,2 GB
--   · le 8 tabelle piu' grandi fanno gia' ~840 MB: sys_skill_embeddings da sola
--     ne pesa 372, cioe' quasi TRE VOLTE l'intera cache del motore
--   · hit ratio cumulativo 87,04% (`stats_reset` e' NULL: non si sa da quando)
--
-- LA PROVA CHE MOSTRA IL DIFETTO MEGLIO DEL RAPPORTO. Una scansione sequenziale
-- ripetuta su `sys.sys_skills` (60 MB con gli indici, ~34 MB di heap) legge
-- 3.892 blocchi DA DISCO a ogni corsa — la prima, la seconda, la terza:
--     CORSA 1  shared hit=399 read=3924   10,6 ms
--     CORSA 2  shared hit=431 read=3892   10,0 ms
--     CORSA 3  shared hit=463 read=3860   10,1 ms
-- Non e' un caso ed e' il punto tecnico di tutta la fase: per una scansione su
-- tabella piu' grande di `shared_buffers/4`, PostgreSQL adotta una strategia ad
-- ANELLO di 256 kB per non spazzare la cache. A 128 MB quella soglia vale 32 MB,
-- e ogni catalogo sopra i 32 MB viene percio' riletto dal disco PER SEMPRE,
-- per quante volte lo si interroghi. A 1 GB la soglia sale a 256 MB e i cataloghi
-- del progetto ci entrano.
--
-- PERCHE' 1 GB E NON I ~2,9 GB DELLA REGOLA DEL 25%. Perche' la macchina non e'
-- sua: ci vivono sette progetti (F8-15) e ha DUE processori. La memoria presa
-- qui e' tolta agli altri inquilini, e lo swap gia' in uso dice che la pressione
-- non e' teorica. 1 GB e' l'8,4% della RAM fisica e il 10% del disponibile:
-- otto volte piu' di prima, e abbastanza piccolo da non spostare l'equilibrio.
-- Il valore si rivede quando cambia la macchina, non quando cambia l'umore.
--
-- ROLLBACK DICHIARATO:
--     ALTER SYSTEM RESET shared_buffers;        -- torna a postgresql.conf: 128MB
--     ALTER SYSTEM RESET effective_cache_size;  -- torna al default: 4GB
--     sudo systemctl restart postgresql@16-main
-- ===========================================================================
ALTER SYSTEM SET shared_buffers = '1GB';

-- `effective_cache_size` NON alloca nulla: dichiara al pianificatore quanta cache
-- puo' aspettarsi in tutto (motore + sistema operativo). Al default dichiarava
-- 4 GB su una macchina che ne ha 11,9 con 8,2 di buff/cache: il pianificatore
-- sceglieva scansioni sequenziali dove un indice sarebbe stato piu' economico.
-- 7 GB e' misurato per difetto — resta sotto il buff/cache reale — e non toglie
-- memoria a nessuno. Context `superuser`: entra col solo reload, senza restart.
ALTER SYSTEM SET effective_cache_size = '7GB';

-- ⚠ TRAPPOLA INCONTRATA, E VERIFICATA PRIMA DI RIAVVIARE (S1077).
-- `pg_settings` riportava `logging_collector | pending_restart = true`, che letto
-- di corsa significa «al prossimo riavvio si accende» — cioe' esattamente cio'
-- che il blocco qui sotto dichiara dannoso su questa macchina. NON e' cosi', e la
-- verifica e' questa: il parametro non compare in `postgresql.auto.conf`, ne' in
-- nessun file sotto `/etc/postgresql/16/main/` (grep ricorsivo, `conf.d` inclusa),
-- e vale `off` in tutti e tre i campi — attivo, `reset_val`, `boot_val`. E' il
-- flag che PostgreSQL 16 alza dopo un `ALTER SYSTEM ... RESET` e non riabbassa
-- piu' fino al riavvio. Dopo il restart resta spento, come deve.
-- Il modo giusto di leggere `pending_restart` e' quindi: guarda anche da DOVE
-- verrebbe il valore nuovo. Se non viene da nessun file, non c'e' valore nuovo.

-- ===========================================================================
-- ⛔ CIO' CHE QUESTO FILE NON FA, E PERCHE' — la parte piu' importante.
--
-- `logging_collector` RESTA SPENTO. Il dossier chiedeva «logging server con
-- rotazione» e la conclusione ovvia era accenderlo. E' sbagliata su questa
-- macchina, e la misura lo ha mostrato:
--
--   · il log su file ESISTE GIA': /var/log/postgresql/postgresql-16-main.log,
--     prodotto dal redirect di stderr che il pacchetto Debian imposta;
--   · la rotazione ESISTE GIA': /etc/logrotate.d/postgresql-common —
--     `weekly, rotate 10, copytruncate, compress`, e i file ruotati fino a
--     `.8.gz` lo dimostrano sul disco.
--
-- Accendere il collector metterebbe DUE meccanismi di rotazione sullo stesso
-- file: PostgreSQL che apre e ruota per conto suo, e logrotate che continua a
-- fare `copytruncate` sotto di lui. Non e' un miglioramento, e' un conflitto.
--
-- Percio' sono stati anche RESETtati i cinque parametri che la prima stesura
-- aveva scritto (log_directory, log_filename, log_rotation_age,
-- log_rotation_size, log_truncate_on_rotation): erano inerti col collector
-- spento, e con il collector acceso sarebbero stati dannosi. Una configurazione
-- inerte non e' innocua — dichiara un'intenzione che il sistema non esegue, e
-- il prossimo che la legge ci crede.
--
-- L'errore iniziale nasce da una misura fatta male, e vale la pena scriverlo:
-- un `ls /var/log/postgresql/ | head -5` aveva mostrato solo i due file di
-- pgbouncer, e da li' era nata la conclusione «PostgreSQL non ha log propri».
-- Il file c'era, piu' in basso nell'elenco. Il taglio era mio, non del sistema.
-- ===========================================================================
