-- db/seeds/brownfield/wave1/00_source_export.sql
-- Wave 1 source export registration (idempotent).
-- Generated by scripts/generate_wave1_seeds.mjs
-- Bundle: docs/source_bundle/brownfield/db-export.zip (sha256=09e5e98c28b701bb008a051e068b731c87bc170d4b4f5bbc8d7a400e81b6e594)

INSERT INTO brownfield.source_exports (
  source_export_name, source_export_file_hash, source_export_retrieved_at,
  source_export_size_bytes, source_export_status, source_export_metadata
) VALUES (
  'db-export-2026-05-15',
  '09e5e98c28b701bb008a051e068b731c87bc170d4b4f5bbc8d7a400e81b6e594',
  '2026-05-15T17:56:00Z'::timestamptz,
  1066682::bigint,
  'INGESTED',
  '{"file_count":35,"schemas_in_zip":["public"],"ingested_by":"wave1_bootstrap","bundle_path":"docs/source_bundle/brownfield/db-export.zip","catalog_source":"docs/source_bundle/brownfield/extracted/catalog.json","notes":"Schema metadata only — no PII row data (per observation 9220 May 17 2026)."}'::jsonb
) ON CONFLICT (source_export_name) DO NOTHING;
