-- db/seeds/brownfield/wave1/03_table_mappings.sql
-- Wave 1 (source_table, canonical_target) mapping rows (idempotent).
-- Generated by scripts/generate_wave1_seeds.mjs
-- All rows: classification=IMPORT, approval_status=APPROVED, target_schema=sys, wave=1.

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'benchmark_configs' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_blueprint_overrides', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"BENCHMARK_CONFIG::<tenant>::<industry>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"INDOOR","all_domains":["INDOOR"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'benchmark_reports' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_blueprint_overrides', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"BENCHMARK_REPORT::<tenant>::<industry>::<period>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"INDOOR","all_domains":["INDOOR"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'business_processes' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_blueprint_process_registry', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"BLUEPRINT_PROCESS::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"process_registry with FK to blueprint variant","primary_domain":"OPOURSKA","all_domains":["OPOURSKA","PROGOV"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ccnl_contracts' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_compensation_bands', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"CCNL::<contract>::<version>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ITLAB","all_domains":["ITLAB"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ccnl_executive_bands' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_compensation_bands', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"CCNL_EXEC_BAND::<contract>::<band>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ITLAB","all_domains":["ITLAB"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ccnl_job_title_mapping' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_job_roles', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"CCNL_JOB_TITLE::<contract>::<level>::<title>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ITLAB","all_domains":["ITLAB"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ccnl_levels' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_compensation_bands', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"CCNL_LEVEL::<contract>::<level>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ITLAB","all_domains":["ITLAB"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ccnl_seniority_rules' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_compensation_bands', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"CCNL_SENIORITY::<contract>::<rule>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ITLAB","all_domains":["ITLAB"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'certification_esco_skills' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_learning_mappings', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"CERT_SKILL::<certification>::<skill>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'certifications' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_user_certifications', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"CERTIFICATION::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"catalog rows; instances per user","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'competencies' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"COMPETENCY::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'competencies' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_categories', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"COMPETENCY_CATEGORY::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"category facet","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'competency_frameworks' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_families', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"COMPETENCY_FRAMEWORK::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'competency_review_ratings' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"COMPETENCY_RATING::<competency>::<level>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"rating-scale attribute","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'course_enrollments' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_paths', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"COURSE_ENROLLMENT::<user>::<course>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"enrollment catalog row (instance ↔ path)","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'course_enrollments_semantic' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_paths', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"COURSE_ENROLLMENT_SEM::<enrollment>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'course_esco_skills' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_learning_mappings', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"COURSE_SKILL::<course>::<skill>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'course_modules' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_path_steps', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"COURSE_MODULE::<course>::<position>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'courses' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_modules', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"LEARNING_MODULE::<scope>::<title_hash>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'cross_entity_relations' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"CROSS_ENTITY_REL::<src>::<tgt>::<type>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'cross_entity_searches' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"CROSS_ENTITY_SEARCH::<query_hash>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"search audit; metadata only","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'esco_isco_groups' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_families', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ISCO_GROUP::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'esco_occupation_skills' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_position_skill_requirements', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ESCO_OCC_SKILL::<occupation>::<skill>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'esco_occupations' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_esco_occupation_mappings', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ESCO_OCCUPATION::<uri>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'esco_skill_groups' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_families', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ESCO_SKILL_GROUP::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'esco_skill_relations' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ESCO_SKILL_REL::<src>::<tgt>::<type>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'esco_skills' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ESCO_SKILL::<uri>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"OPOURSKA","all_domains":["OPOURSKA","ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'extracted_skills' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"EXTRACTED_SKILL::<source>::<text>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'holidays' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_blueprint_overrides', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"HOLIDAY::<country>::<date>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"holiday catalog override","primary_domain":"ITLAB","all_domains":["ITLAB"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'import_skill_links' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"IMPORT_SKILL_LINK::<source>::<target>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO","DGOV"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'industry_ccnl_mapping' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_activity_classification_mappings', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ATECO_CCNL::<ateco>::<ccnl>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"INDOOR","all_domains":["INDOOR","ITLAB"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'industry_classifications' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_activity_classifications', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ATECO_2025::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"INDOOR","all_domains":["INDOOR"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'industry_classifications' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_activity_classifications', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"NACE_REV_2_1::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"NACE variant","primary_domain":"INDOOR","all_domains":["INDOOR"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'industry_occupation_mapping' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_esco_occupation_mappings', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"INDUSTRY_OCC::<industry>::<occupation>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"INDOOR","all_domains":["INDOOR"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'industry_profiles' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_activity_classifications', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"INDUSTRY_PROFILE::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"INDOOR","all_domains":["INDOOR"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'job_template_skills' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_position_skill_requirements', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"POSITION_SKILL::<position_id>::<skill_id>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"derived from job_template instantiation","primary_domain":"OPOURSKA","all_domains":["OPOURSKA"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'job_templates' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_job_roles', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"JOB_ROLE::<family>::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"OPOURSKA","all_domains":["OPOURSKA"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'job_title_courses' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_learning_mappings', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"JOB_TITLE_COURSE::<title>::<course>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"H2R","all_domains":["H2R"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'job_title_learning_paths' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_position_learning_requirements', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"JOB_TITLE_PATH::<title>::<path>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"H2R","all_domains":["H2R"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'learning_bookmarks' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_modules', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"LEARNING_BOOKMARK::<user>::<module>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'learning_content_providers' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_modules', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"CONTENT_PROVIDER::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'learning_path_courses' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_path_steps', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"PATH_COURSE::<path>::<course>::<order>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'learning_path_enrollments' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_paths', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"PATH_ENROLLMENT::<user>::<path>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'learning_paths' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_paths', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"LEARNING_PATH::<tenant>::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'learning_ratings' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_modules', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"LEARNING_RATING::<module>::<rater>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'learning_recommendations' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_modules', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"LEARNING_REC::<user>::<module>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'market_benchmarks' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"MARKET_BENCHMARK::<industry>::<role>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"skill market intelligence","primary_domain":"INDOOR","all_domains":["INDOOR"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'market_salary_data' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"MARKET_SALARY::<role>::<region>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"skill compensation overlay (Wave1 catalog only)","primary_domain":"INDOOR","all_domains":["INDOOR"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'module_completions' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_modules', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"MODULE_COMPLETION::<user>::<module>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'occupation_industry_classifications' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_esco_occupation_mappings', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"OCC_INDUSTRY::<occupation>::<industry>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"INDOOR","all_domains":["INDOOR"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_abilities' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_ABILITY::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_esco_mappings' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_ESCO::<onet>::<esco>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_import_jobs' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_IMPORT_JOB::<job_id>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"job metadata only","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_knowledge' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_KNOWLEDGE::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_occupation_abilities' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_position_skill_requirements', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_OCC_ABILITY::<occupation>::<ability>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_occupation_knowledge' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_position_skill_requirements', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_OCC_KNOWLEDGE::<occupation>::<knowledge>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_occupation_skills' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_position_skill_requirements', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_OCC_SKILL::<occupation>::<skill>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_occupation_work_activities' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_position_skill_requirements', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_OCC_WORK_ACT::<occupation>::<activity>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_occupations' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_esco_occupation_mappings', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_OCCUPATION::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_skills' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_SKILL::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'onet_work_activities' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONET_WORK_ACTIVITY::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ontology_categories' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_categories', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONTOLOGY_CATEGORY::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ontology_embedding_jobs' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONTOLOGY_EMBED_JOB::<job_id>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"AI job metadata","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ontology_feedback' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONTOLOGY_FEEDBACK::<entity>::<rater>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ontology_inference_jobs' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONTOLOGY_INFER_JOB::<job_id>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ontology_quality_metrics' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONTOLOGY_QUALITY::<metric>::<period>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ontology_skill_dimensions' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONTOLOGY_SKILL_DIM::<skill>::<dimension>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ontology_skill_relations' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONTOLOGY_SKILL_REL::<src>::<tgt>::<type>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'ontology_source_mappings' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"ONTOLOGY_SRC_MAP::<src_system>::<src_id>::<canonical_id>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'process_kpis' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_process_kpi_templates', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"FIN_BANKING_KPI::<process_code>::<kpi_code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"PROGOV","all_domains":["PROGOV"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'process_phases' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_blueprint_process_registry', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"PROCESS_PHASE::<process>::<phase>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"embedded as process_registry.metadata.phases","primary_domain":"PROGOV","all_domains":["PROGOV"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'rating_scales' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"RATING_SCALE::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"scale catalog metadata","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'semantic_entity_index' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SEMANTIC_INDEX::<entity_type>::<entity_id>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'semantic_entity_relations' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SEMANTIC_REL::<src>::<tgt>::<type>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'semantic_search_log' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SEMANTIC_SEARCH::<query_hash>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"search audit; metadata only","primary_domain":"ESKAP","all_domains":["ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'sindacati' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_compensation_bands', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SINDACATO::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"union reference (REFERENCE_ONLY in MAP §4.10; promoted to band overlay for Wave 1 import)","primary_domain":"ITLAB","all_domains":["ITLAB"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_adjacencies' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_ADJACENCY::<skill_a>::<skill_b>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO","ESKAP"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_aliases' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_aliases', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_ALIAS::<skill>::<alias>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_classifications' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_categories', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_CLASSIFICATION::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_clusters' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_families', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_CLUSTER::<code>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_demand_metrics' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_DEMAND::<skill>::<period>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_development_paths' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_learning_paths', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_DEV_PATH::<skill>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_extraction_jobs' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_EXTRACT_JOB::<job_id>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","transform_hint":"job metadata only","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_gap_analyses' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_GAP::<tenant>::<period>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_gap_snapshots' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_GAP_SNAP::<tenant>::<period>::<seq>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_matrices' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_MATRIX::<row>::<col>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_migration_jobs' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_MIGRATION_JOB::<job_id>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_pair_usage' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_PAIR::<skill_a>::<skill_b>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_relationships' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_RELATIONSHIP::<skill_a>::<skill_b>::<type>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_requirements_templates' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_position_skill_requirements', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_REQ_TEMPLATE::<template>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_supply_metrics' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_SUPPLY::<skill>::<period>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_synonyms' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_aliases', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_SYNONYM::<skill>::<synonym>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'skill_taxonomy_extensions' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skill_taxonomy_edges', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"SKILL_TAXONOMY_EXT::<source>::<target>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'tenant_industry_classifications' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_blueprint_overrides', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"TENANT_INDUSTRY::<tenant>::<industry>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"INDOOR","all_domains":["INDOOR"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;

WITH src AS (
  SELECT source_table_id FROM brownfield.source_tables
  WHERE source_table_name = 'unknown_skills' AND source_table_schema = 'public'
    AND source_table_export_id = (SELECT source_export_id FROM brownfield.source_exports
        WHERE source_export_name = 'db-export-2026-05-15')
)
INSERT INTO brownfield.table_mappings (
  table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table,
  table_mapping_classification, table_mapping_approval_status,
  table_mapping_approved_at, table_mapping_rationale, table_mapping_metadata,
  table_mapping_wave
)
SELECT src.source_table_id, 'sys', 'sys_skills', 'IMPORT', 'APPROVED',
  now(), 'Wave 1 auto-approval per BROWNFIELD_IMPORT_PLAN.md §3.', '{"natural_key_pattern":"UNKNOWN_SKILL::<text>","auto_approver_rule":"WAVE_1_AUTO_APPROVE","primary_domain":"SKILGRO","all_domains":["SKILGRO"]}'::jsonb, 1
FROM src
ON CONFLICT (table_mapping_source_table_id, table_mapping_target_schema, table_mapping_target_table) DO NOTHING;
