-- ============================================================================
-- 000339 — #220 W1.4 (rilievi F5-02, F5-07): i quindici cataloghi acquistano
--          un registro delle modifiche, e il timestamp di ultima modifica.
--
-- IL DIFETTO, misurato sul vivo il 2026-08-20 (non ereditato dal dossier):
--   · schema `audit`: 11 tabelle, TUTTE archivi di purghe deliberate piu'
--     `user_self_service_actions`. Nessun registro generico delle modifiche.
--   · 110 trigger in `sys`, di cui 93 sono `sys_set_updated_at`: esiste un
--     pattern diffuso, ma NON copre i cataloghi.
--   · dei 15 cataloghi, 5 hanno il trigger di timestamp e 10 no; di quei 10,
--     quattro non hanno nemmeno la colonna.
--   Conseguenza: una modifica a mano a un catalogo non lasciava alcuna traccia.
--
-- ⚠ IL TRIGGER REGISTRA SOLO I CAMBIAMENTI VERI, e non e' un dettaglio di
-- eleganza: e' cio' che rende questa migrazione sicura da applicare ORA.
-- Il rilievo F3-02 (voce #223 W4.1, ancora aperta) dice che
-- `upsertEscoSkillHierarchy` esegue un UPDATE incondizionato e riscriverebbe
-- ~14.000 righe IDENTICHE a ogni corsa di sincronizzazione. Un audit ingenuo
-- trasformerebbe ogni corsa in 14.000 righe di registro — cioe' un presidio
-- che si autodistrugge per volume, e per giunta rende invisibile la modifica
-- vera in mezzo al rumore.
-- Confrontando `to_jsonb(OLD)` con `to_jsonb(NEW)` il registro resta corretto
-- **a prescindere** da quando F3-02 verra' corretto, e protegge anche dai
-- prossimi upsert ciechi che nessuno ha ancora scritto.
--
-- ROLLBACK DICHIARATO: nessun giornale `staging.*_undo`. Questa migrazione
-- AGGIUNGE (una tabella, una funzione, dei trigger, quattro colonne nullable) e
-- non modifica alcuna riga esistente: non c'e' nulla da conservare per poterlo
-- ripristinare. L'inversa e' `DROP TRIGGER` piu' `DROP TABLE audit.catalog_changes`.
--
-- IDEMPOTENTE: `IF NOT EXISTS` ovunque, `CREATE OR REPLACE` per la funzione,
-- `DROP TRIGGER IF EXISTS` prima di ogni `CREATE TRIGGER`.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS audit;

-- ---------------------------------------------------------------------------
-- 1. Il registro
--
-- `operation` e' varchar + CHECK, non un ENUM (RD-08).
-- `old_row`/`new_row` sono jsonb interi: conservare l'intera riga costa poco su
-- tabelle che cambiano di rado, e sopravvive all'aggiunta di colonne future —
-- un elenco di campi scelti oggi invecchierebbe in silenzio.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.catalog_changes (
  catalog_change_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  changed_at         timestamptz  NOT NULL DEFAULT now(),
  table_name         text         NOT NULL,
  operation          varchar(10)  NOT NULL
                     CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
  db_user            text         NOT NULL DEFAULT current_user,
  application_name   text,
  old_row            jsonb,
  new_row            jsonb
);

COMMENT ON TABLE audit.catalog_changes IS
  'Registro delle modifiche ai cataloghi (#220 W1.4, rilievo F5-02). Solo cambiamenti reali: un UPDATE che non cambia nulla non produce una riga.';

CREATE INDEX IF NOT EXISTS idx_catalog_changes_table_time
  ON audit.catalog_changes (table_name, changed_at DESC);

-- ---------------------------------------------------------------------------
-- 2. La funzione
--
-- AFTER, non BEFORE: un registro deve dire cio' che E' avvenuto, non cio' che
-- sta per avvenire — con BEFORE, una modifica annullata a valle resterebbe
-- scritta come se fosse successa.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION audit.fn_catalog_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  -- Un UPDATE che non cambia niente non e' una modifica. Vedi l'avvertenza in
  -- testa al file: senza questa riga, una corsa di reference-sync scriverebbe
  -- migliaia di voci che raccontano che nulla e' cambiato.
  --
  -- ⚠ `updated_at` VA TOLTO DAL CONFRONTO, e la prima stesura non lo faceva.
  -- Il difetto e' emerso solo provandolo sul vivo: un UPDATE a vuoto produceva
  -- comunque la sua riga di registro. La causa e' l'ordine dei trigger — il
  -- BEFORE `sys_set_updated_at` scrive `NEW.updated_at := now()` PRIMA che
  -- questo AFTER guardi le due versioni, quindi OLD e NEW differiscono SEMPRE,
  -- almeno per quel campo. Il confronto su `to_jsonb` intero era percio' un
  -- filtro che non filtrava niente, e la protezione dichiarata qui sopra era
  -- una dichiarazione, non un fatto.
  --
  -- (Nota che resta aperta: `sys_set_updated_at` muove il timestamp anche
  -- quando nulla cambia davvero, su tutte e 93 le tabelle che lo usano. E' un
  -- difetto preesistente e piu' largo di questo file — appartiene a #223 W4.1,
  -- che tratta gli UPDATE incondizionati.)
  IF TG_OP = 'UPDATE'
     AND (to_jsonb(OLD) - 'updated_at') IS NOT DISTINCT FROM (to_jsonb(NEW) - 'updated_at') THEN
    RETURN NULL;
  END IF;

  INSERT INTO audit.catalog_changes
         (table_name, operation, application_name, old_row, new_row)
  VALUES (TG_TABLE_NAME,
          TG_OP,
          nullif(current_setting('application_name', true), ''),
          CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) END,
          CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) END);

  RETURN NULL;  -- AFTER trigger: il valore di ritorno e' ignorato
END $$;

-- ---------------------------------------------------------------------------
-- 3. Le quattro colonne `updated_at` che mancavano (F5-07)
--
-- NULLABLE E SENZA DEFAULT, per due ragioni distinte:
--   · onesta' — le righe gia' presenti non hanno una data di modifica nota, e
--     scrivergli `now()` inventerebbe che sono state modificate oggi. E' lo
--     stesso difetto che il rilievo F7-02 contesta ai vettori ricalcolati
--     (min=max=2026-06-06 su testo cambiato dopo): un timestamp falso e' peggio
--     di un timestamp assente, perche' sembra un'informazione.
--   · costo — `ADD COLUMN ... DEFAULT now()` con una default VOLATILE riscrive
--     l'intera tabella. Qui sarebbero 18.420 archi + 14.036 vettori + 3.045
--     vettori occupazione (misurati oggi): una riscrittura inutile.
-- ---------------------------------------------------------------------------
ALTER TABLE sys.sys_skill_aliases              ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE sys.sys_skill_taxonomy_edges       ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE sys.sys_skill_embeddings           ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE sys.sys_esco_occupation_embeddings ADD COLUMN IF NOT EXISTS updated_at timestamptz;

-- ---------------------------------------------------------------------------
-- 4. I trigger, sui quindici cataloghi
--
-- ELENCO ESPLICITO, MAI UN JOLLY. Un ciclo su `information_schema` avrebbe
-- preso anche le tabelle operative che portano gli stessi nomi — `sys_user_skills`,
-- `sys_position_skill_requirements`, `sys_skill_gap_scores` — che NON sono
-- cataloghi: sono dati di tenant, cambiano di continuo, e metterci un audit
-- generico significherebbe un registro che cresce senza controllo.
--
-- I quindici sono quelli che il dossier misura in F5-07: i cinque che avevano
-- gia' il timestamp, piu' i dieci che non l'avevano.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  tab      text;
  cataloghi text[] := ARRAY[
    -- i cinque che avevano gia' `sys_set_updated_at`
    'sys_skills',
    'sys_activity_classifications',
    'sys_occupation_classifications',
    'sys_occupation_classification_mappings',
    'sys_occupation_skill_requirements',
    -- i dieci che non l'avevano
    'sys_skill_aliases',
    'sys_skill_taxonomy_edges',
    'sys_skill_groups',
    'sys_skill_categories',
    'sys_skill_families',
    'sys_skill_embeddings',
    'sys_esco_occupation_mappings',
    'sys_esco_occupation_embeddings',
    'sys_reference_translations',
    'sys_activity_classification_mappings'
  ];
  ha_updated_at boolean;
BEGIN
  FOREACH tab IN ARRAY cataloghi LOOP
    CONTINUE WHEN NOT EXISTS (
      SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
       WHERE n.nspname = 'sys' AND c.relname = tab AND c.relkind = 'r');

    -- 4a. il registro delle modifiche
    EXECUTE format('DROP TRIGGER IF EXISTS trg_audit_catalog ON sys.%I', tab);
    EXECUTE format(
      'CREATE TRIGGER trg_audit_catalog AFTER INSERT OR UPDATE OR DELETE ON sys.%I '
      'FOR EACH ROW EXECUTE FUNCTION audit.fn_catalog_change()', tab);

    -- 4b. il timestamp, solo dove la colonna c'e' (le quattro aggiunte sopra
    --     piu' quelle che l'avevano gia'). Riusa la funzione del progetto,
    --     `sys.sys_set_updated_at`, che gia' governa 93 tabelle: introdurne una
    --     seconda con lo stesso compito sarebbe una divergenza in attesa.
    SELECT EXISTS (SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'sys' AND table_name = tab
                      AND column_name = 'updated_at')
      INTO ha_updated_at;

    IF ha_updated_at THEN
      EXECUTE format('DROP TRIGGER IF EXISTS trg_set_updated_at ON sys.%I', tab);
      EXECUTE format(
        'CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON sys.%I '
        'FOR EACH ROW EXECUTE FUNCTION sys.sys_set_updated_at()', tab);
    END IF;
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 5. POST-CONDIZIONE
--
-- Il secondo controllo protegge cio' che NON doveva cambiare: le tabelle
-- OPERATIVE con nomi simili devono essere rimaste fuori. Contare solo i 15
-- coperti non distinguerebbe «ho preso i cataloghi» da «ho preso mezzo schema»,
-- che e' il guasto piu' probabile di un file che installa trigger in massa.
-- ---------------------------------------------------------------------------
DO $$
DECLARE coperti int; invasi int;
BEGIN
  SELECT count(*) INTO coperti
    FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'sys' AND t.tgname = 'trg_audit_catalog' AND NOT t.tgisinternal;
  IF coperti <> 15 THEN
    RAISE EXCEPTION '000339: attesi 15 cataloghi con registro, trovati %', coperti;
  END IF;

  SELECT count(*) INTO invasi
    FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'sys' AND t.tgname = 'trg_audit_catalog'
     AND c.relname IN ('sys_user_skills', 'sys_position_skill_requirements',
                       'sys_skill_gap_scores', 'sys_user_skill_evidence',
                       'sys_blueprint_content_skills', 'sys_skill_learning_mappings',
                       'sys_user_profile_embeddings', 'sys_job_role_embeddings',
                       'sys_position_skill_requirement_history');
  IF invasi > 0 THEN
    RAISE EXCEPTION '000339: % tabelle OPERATIVE hanno preso il registro dei cataloghi', invasi;
  END IF;

  RAISE NOTICE '000339 ok — 15 cataloghi con registro, 0 tabelle operative toccate';
END $$;
