-- 000452 — #253: il diario del gate diventa interrogabile.
--
-- IL FATTO, misurato S1101. Il diario del write-gate (`apps/agent-gateway`, M-4) scrive
-- un JSONL append-only (`FileAuditSink`, `.data/agent-audit.jsonl`) e non porta un
-- identificativo di conversazione: non si puo' chiedere al database «quante persone
-- distinte ha toccato ogni conversazione» (ADR-0040 R2, #251/#252), solo grep il file.
--
-- LA DECISIONE (gia' presa, #253, vale il veto). La casa del diario e' `audit.*`: schema
-- ausiliario dichiarato in I3/I4, come gli altri undici registri che vi abitano gia'
-- (mig. 000002, 000339). Non e' un dato di dominio (I5 non si applica: nessun filtro di
-- tenant nel middleware serve qui, la riga porta gia' il proprio `tenant` testuale) ed e'
-- scritta dal gateway con la propria identita' meno potente (#223 F3), non dall'API.
-- `FileAuditSink` resta il fallback dove non c'e' un database configurato
-- (`apps/agent-gateway/src/server.ts` sceglie fra i due sink guardando `POSTGRES_HOST`).
--
-- CHE COSA AGGIUNGE. Una tabella con una riga per decisione del gate (stessa forma di
-- `AuditEntry`, `apps/agent-gateway/src/audit-sink.ts`) e una vista INFORMATIVA in `sys`
-- (dove vivono le sentinelle: `db_health.py` scopre SOLO `sys.v_*`, mai `audit.v_*`) che
-- espone, per conversazione, il numero finale di persone distinte — la voce di CHIUSURA
-- scritta da `registraChiusuraConversazione`, `reason = 'CONVERSAZIONE_CHIUSA'`.
--
-- PERCHE' INFORMATIVA E NON SENTINELLA. La vista conta stato (quante persone ha letto
-- ogni conversazione), non un'anomalia: una conversazione che tocca 160 persone non e'
-- un difetto, e' il freno di `#252` che ha gia' fatto il suo lavoro se serviva. Zero righe
-- e' l'atteso finche' il diario non ha ancora scritto nessuna chiusura (gateway spento,
-- o database appena collegato) — pretendere righe >0 farebbe rossa una prova generale
-- che non ha ancora nessun dato da mostrare.
--
-- IDEMPOTENTE: `CREATE TABLE IF NOT EXISTS`, `CREATE INDEX IF NOT EXISTS`,
-- `CREATE OR REPLACE VIEW`. ROLLBACK DICHIARATO: nessun giornale `staging.*_undo` — questa
-- migrazione AGGIUNGE (una tabella, due indici, una vista) e non tocca righe esistenti;
-- l'inversa e' `DROP VIEW sys.v_agente_persone_per_conversazione` +
-- `DROP TABLE audit.agent_gateway_decisions`.
--
-- CENSIMENTO (chi_sorveglia.py, prima di scrivere): nessuna sentinella, nessun cancello,
-- nessuno scrittore, nessuna migrazione precedente — l'oggetto e' nuovo.

BEGIN;

CREATE SCHEMA IF NOT EXISTS audit; -- gia' esistente da 000002; idempotente per costruzione

-- ---------------------------------------------------------------------------
-- 1. Il diario, in forma di riga (una per decisione del gate)
--
-- Campi categoriali = varchar + CHECK (RD-08), mai ENUM. `ts` e' timestamptz perche' un
-- diario di decisioni vive e muore sull'ordine e sull'orario esatto (RD-09).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.agent_gateway_decisions (
  decision_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id     uuid,           -- NULL = chi monta il gate senza runHrAgent (test)
  ts                  timestamptz  NOT NULL,
  principal_kind      varchar(10)  NOT NULL
                       CHECK (principal_kind IN ('user', 'service', 'unknown')),
  principal_subject   text,
  tenant              text         NOT NULL,
  tool                text         NOT NULL,
  args_hash           text         NOT NULL,
  concept             text,
  operation           text,
  persone_distinte    integer,
  livello_persone     varchar(20)  CHECK (
                         livello_persone IS NULL
                         OR livello_persone IN ('silenzioso', 'dichiarato', 'confermato', 'non-misurato')
                       ),
  decision            varchar(10)  NOT NULL CHECK (decision IN ('allow', 'deny')),
  reason              text         NOT NULL,
  recorded_at         timestamptz  NOT NULL DEFAULT now()
);

COMMENT ON TABLE audit.agent_gateway_decisions IS
  '#253 — il diario del write-gate dell''agente (apps/agent-gateway), interrogabile. Home del '
  'DbAuditSink; FileAuditSink (.data/agent-audit.jsonl) resta il fallback senza database. Una '
  'riga per decisione (allow/deny); la voce di chiusura di una conversazione ha reason = '
  'CONVERSAZIONE_CHIUSA e porta il totale finale di persone_distinte (#251/#252, ADR-0040).';

CREATE INDEX IF NOT EXISTS idx_agent_gateway_decisions_conversation
  ON audit.agent_gateway_decisions (conversation_id);
CREATE INDEX IF NOT EXISTS idx_agent_gateway_decisions_ts
  ON audit.agent_gateway_decisions (ts);

-- ---------------------------------------------------------------------------
-- 2. La vista informativa, in `sys` (dove `db_health.py` scopre le sentinelle)
--
-- Chiuso-quando (#253, dal register): `select conversazione, persone_distinte from
-- sys.v_agente_persone_per_conversazione` risponde sul vivo.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW sys.v_agente_persone_per_conversazione AS
SELECT
  conversation_id AS conversazione,
  persone_distinte,
  livello_persone,
  tenant,
  ts AS chiusa_il
FROM audit.agent_gateway_decisions
WHERE reason = 'CONVERSAZIONE_CHIUSA'
  AND conversation_id IS NOT NULL;

COMMENT ON VIEW sys.v_agente_persone_per_conversazione IS
  '#253 — INFORMATIVA (db_health.py, INFORMATIVE): una riga per conversazione chiusa, col '
  'totale finale di persone distinte lette (ADR-0040 R2). Zero righe e'' l''atteso finche'' il '
  'diario non ha ancora scritto una chiusura; righe con numeri alti non sono un difetto, sono '
  'il freno di #252 che ha gia'' fatto il suo lavoro se serviva.';

-- ---------------------------------------------------------------------------
-- 3. Guardia — la vista esiste, e' in `sys` (non altrove), e conta senza esplodere.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  n_viste  integer;
  n_righe  integer;
BEGIN
  SELECT count(*) INTO n_viste
    FROM pg_views
   WHERE schemaname = 'sys' AND viewname = 'v_agente_persone_per_conversazione';
  IF n_viste <> 1 THEN
    RAISE EXCEPTION '000452: sys.v_agente_persone_per_conversazione non trovata (%)', n_viste;
  END IF;

  SELECT count(*) INTO n_righe FROM sys.v_agente_persone_per_conversazione;
  RAISE NOTICE '000452 ok: vista creata, % righe (atteso 0 finche'' nessuna conversazione ha chiuso via DB)', n_righe;
END $$;

COMMIT;

-- FINE 000452
