#Requires -Version 5.1
<#
.SYNOPSIS
    Convenience launcher for the Cowork v2.2 R6 pending-manifest pattern
    applied to the 2026-05-19 session.

.DESCRIPTION
    Runs `node scripts/cowork-exchange/apply-pending.mjs` from the repo root.
    The manifest at `cowork_code_exchange/.cowork-pending-commits.json` was
    prepared by Cowork Desktop and contains 6 atomic commits + push directive.

    This script is the explicit fallback for the case where CLI is not in an
    interactive session that can auto-consume the manifest. Running it produces
    the same effect as `pnpm cowork:apply-pending`.

.PARAMETER DryRun
    Pass --dry-run to apply-pending.mjs.

.PARAMETER NoPush
    Pass --no-push to apply-pending.mjs (apply commits locally only).

.NOTES
    Generated by Cowork Desktop, 2026-05-19. Codified by README v2.2 R6.
    Idempotent: safe to re-run; if manifest already archived, exits with "nothing to do".
#>

param(
    [switch]$DryRun,
    [switch]$NoPush
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$REPO_ROOT = "D:\heuresys-advanced"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $color = switch ($Level) {
        "OK"    { "Green"  }
        "WARN"  { "Yellow" }
        "ERROR" { "Red"    }
        "STEP"  { "Cyan"   }
        default { "White"  }
    }
    Write-Host "[$ts][$Level] $Message" -ForegroundColor $color
}

if (-not (Test-Path $REPO_ROOT)) {
    Write-Log "Repo root not found: $REPO_ROOT" "ERROR"
    exit 2
}

Set-Location $REPO_ROOT

if (-not (Test-Path "cowork_code_exchange\.cowork-pending-commits.json")) {
    Write-Log "No manifest at cowork_code_exchange\.cowork-pending-commits.json -- nothing to apply" "WARN"
    Write-Log "(if previously applied, see cowork_code_exchange\.cowork-pending-commits\applied\ for archive)" "INFO"
    exit 0
}

Write-Log "=== Cowork v2.2 R6 -- Pending-manifest apply ===" "STEP"
Write-Log "Manifest: cowork_code_exchange\.cowork-pending-commits.json" "INFO"

# Ensure node is available
$node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node) {
    Write-Log "node.exe not in PATH" "ERROR"
    exit 3
}

$nodeArgs = @("scripts\cowork-exchange\apply-pending.mjs")
if ($DryRun) { $nodeArgs += "--dry-run" }
if ($NoPush) { $nodeArgs += "--no-push" }

Write-Log "Executing: node $($nodeArgs -join ' ')" "STEP"
Write-Log ""

& node $nodeArgs
$rc = $LASTEXITCODE

Write-Log ""
if ($rc -eq 0) {
    Write-Log "apply-pending completed successfully" "OK"
}
else {
    Write-Log "apply-pending exited with code $rc" "ERROR"
}

exit $rc
